### ISSUE TITLE
Lỗi không cài được 

### ISSUE THREAD

**Issue by h26v** [catalizcs/miraiv2#43]
![image](https://user-images.githubusercontent.com/59920945/118747526-5ff4ba80-b884-11eb-9c0b-cc219b38a7d4.png)
![image](https://user-images.githubusercontent.com/59920945/118747534-62efab00-b884-11eb-9a3b-72385cf85e07.png)
![image](https://user-images.githubusercontent.com/59920945/118747538-65520500-b884-11eb-9bcb-ca4031bff872.png)
Lỗi ở tập lệnh canvas@2.8.0 tôi k thể cài được bot

**Comment by catalizcs** [comment]
thiếu GTK, cách cài thì [ở đây](https://github.com/Automattic/node-canvas/wiki/Installation%3A-Windows#2-installing-gtk-2)

**Comment by h26v** [comment]
![image](https://user-images.githubusercontent.com/59920945/118906199-7e6fba00-b947-11eb-9375-3495dd4873dc.png)
Lỗi khi cài các module cho bot 😢

**Comment by catalizcs** [comment]
chuyển qua bản [features](https://github.com/catalizcs/miraiv2/tree/features) mà sử dụng, bản main nhiều lỗi chưa fix

**Comment by h26v** [comment]
> chuyển qua bản [features](https://github.com/catalizcs/miraiv2/tree/features) mà sử dụng, bản main nhiều lỗi chưa fix

Tôi thề là cài mà muốn ngồi khóc mẹ luôn 😭
