### ISSUE TITLE
Tập lệnh cài đặt windows-build-tools bị treo

### ISSUE THREAD

**Issue by h26v** [catalizcs/miraiv2#44]
![image](https://user-images.githubusercontent.com/59920945/118748816-959aa300-b886-11eb-911d-beaebefbf5c1.png)

**Comment by catalizcs** [comment]
cái này do mạng mà ?

**Comment by h26v** [comment]
> cái này do mạng mà ?

Mạng full cây mà treo gần 1h chưa thấy xong :<

**Comment by catalizcs** [comment]
băng thông quốc tế suck :ok_hand:

**Comment by h26v** [comment]
Đóng vấn đề nay thôi, thanks bro 💯
